apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik.sof-k8s.storpool.net
  name: karma
  namespace: internal-monitoring
spec:
  entryPoints:
  - webinternal
  routes:
  - kind: Rule
    match: Host(`internal-alerts.storpool.local`)
    services:
    - name: karma
      port: 80
  - kind: Rule
    match: Host(`internal-alerts.storpool.net`)
    services:
    - name: karma
      port: 80
  - kind: Rule
    match: Host(`internal-alerts.sof-k8s.storpool.net`)
    services:
    - name: karma
      port: 80
